-- Structured Morning Briefs generated by Chief AI
create table public.briefs (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references public.profiles(id) on delete cascade,
  brief_date   date not null,
  type         text default 'morning',
  greeting     text,
  sections     jsonb not null default '[]',
  life_debt    jsonb,
  generated_by text default 'claude',
  model        text,
  created_at   timestamptz default now(),
  unique(user_id, brief_date, type)
);
alter table public.briefs enable row level security;
create policy "Users see own briefs"
  on public.briefs for all
  using (auth.uid() = user_id);
create index briefs_user_date on public.briefs(user_id, brief_date desc);

-- Goal check-ins: history of each Morning Brief + Weekly Replay
create table public.goal_check_ins (
  id                 uuid primary key default gen_random_uuid(),
  user_id            uuid not null references public.profiles(id) on delete cascade,
  type               text not null,
  brief_id           uuid references public.briefs(id),
  highlights         text[],
  lowlights          text[],
  patterns_noticed   text[],
  momentum_start     integer,
  momentum_end       integer,
  goals_reviewed     text[],
  actions_planned    text[],
  actions_completed  text[],
  narrative          text,
  created_at         timestamptz default now()
);
alter table public.goal_check_ins enable row level security;
create policy "Users own their check-ins"
  on public.goal_check_ins for all
  using (auth.uid() = user_id);
create index check_ins_user_type on public.goal_check_ins(user_id, type, created_at desc);
